name: flexurio_chiron_purchase_order
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  gap: ^3.0.1
  easy_localization: ^3.0.2
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.2.0
  page_transition: ^2.0.9
  file_picker: ^5.2.5
  appointment:
    path: ../../
  flexurio_chiron_production:
    path: ../flexurio_chiron_production/
  flexurio_erp_authentication:
    path: ../flexurio_erp_authentication/
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  flutter:
    sdk: flutter
  hydrated_bloc: ^8.1.0
  font_awesome_flutter: ^10.7.0
  dio: ^4.0.0


dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.5.4
  build_runner_core: ^7.2.9
  freezed: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/