class FinanceCustomer {
  FinanceCustomer({required this.id, required this.name});

  final String id;
  final String name;
}

final financeCustomers = [
  FinanceCustomer(name: 'ACENG KOMARUDIN', id: 'ACENG'),
  FinanceCustomer(name: 'AFIF AFANDI', id: 'AFIF'),
  FinanceCustomer(name: 'Afrida', id: 'IBUAFRIDA'),
  FinanceCustomer(name: 'Agung', id: 'BPAGUNG'),
  FinanceCustomer(name: 'AGUSTINUS INDERAYANA', id: 'AGUS'),
  FinanceCustomer(name: 'Agustinus', id: 'BPAGUSTINU'),
  FinanceCustomer(name: 'AMELIA ARSYL', id: 'AMEL'),
  FinanceCustomer(name: 'Anastasia Budiman', id: 'IBUANAS'),
  FinanceCustomer(name: 'ANDRIANI RAHAJUNINGSIH', id: 'ANDRIANI R'),
  FinanceCustomer(name: 'ANDRIATI OMAR', id: 'ANDRI'),
  FinanceCustomer(name: 'Andy', id: 'BPANDY'),
  FinanceCustomer(name: 'ANES SOPENDI', id: 'BPANES'),
  FinanceCustomer(name: 'ANITA DEWI WIDIYANTI', id: 'ANITAD'),
  FinanceCustomer(name: 'ANNISAA', id: 'ANNISAA'),
  FinanceCustomer(name: 'APOTEK RAKYAT KOMPLIT', id: 'KOMPLIT'),
  FinanceCustomer(name: 'Apotik Cemara', id: 'APCEMARA'),
  FinanceCustomer(name: 'APOTIK JOHANAS JOHAN', id: 'AJJ'),
  FinanceCustomer(name: 'Apotik Yudistira', id: 'APYUDIS'),
  FinanceCustomer(name: 'APT.MAHKOTA', id: 'MAHKOTA'),
  FinanceCustomer(name: 'AROFAL OTC', id: 'ARO'),
  FinanceCustomer(name: 'Arya', id: 'BPARYA'),
  FinanceCustomer(name: 'ASEP MULYANA GUNAWAN', id: 'ASEP M G'),
  FinanceCustomer(name: 'Asnah', id: 'IBUASNAH'),
  FinanceCustomer(name: 'AULINA MUTIARAWATI', id: 'AULINA'),
  FinanceCustomer(name: 'Ayub Heriawan', id: 'BPAYUB'),
  FinanceCustomer(name: 'Bidan Ny. Pauline', id: 'PAULINE'),
  FinanceCustomer(name: 'BOYKE YULIAN EFFENDI', id: 'BOYKE'),
  FinanceCustomer(name: 'Bp. Robi', id: 'ROBIHO'),
  FinanceCustomer(name: 'BPK. ADHY SULAKSONO', id: 'ADHY'),
  FinanceCustomer(name: 'Bpk. Andi', id: 'ANDI'),
  FinanceCustomer(name: 'Bpk. Edi Prasetiyo', id: 'EDI'),
  FinanceCustomer(name: 'Bpk. Zulhaq Rahdiyanto', id: 'BPZUL'),
  FinanceCustomer(name: 'BUDI MULYADI MUSLIM', id: 'BUDI M M'),
  FinanceCustomer(name: 'Business Development', id: 'BUSDEV'),
  FinanceCustomer(name: 'CASH / TUNAI', id: 'TU'),
  FinanceCustomer(name: 'Dame Twelviera', id: 'IBUDAME'),
  FinanceCustomer(name: 'Danny Yudianto', id: 'BPDANNY'),
  FinanceCustomer(name: 'DARWIS', id: 'DARWIS'),
  FinanceCustomer(name: 'David Tjahjaputra', id: 'BPDAVID'),
  FinanceCustomer(name: 'Denny', id: 'BPDENNY'),
  FinanceCustomer(name: 'Department QA', id: 'QA'),
  FinanceCustomer(name: 'Devia Melina', id: 'IBUDEVIA'),
  FinanceCustomer(name: 'DIANA WIDYASTUTI', id: 'DW'),
  FinanceCustomer(name: 'DICKY LESMANA', id: 'DICKY L'),
  FinanceCustomer(name: 'DIGITAL MARKETING', id: 'DM'),
  FinanceCustomer(name: 'DITA FAUTHIA BARKAH', id: 'DITA'),
  FinanceCustomer(name: 'DONI AZMAR.SF.APT', id: 'DONI'),
  FinanceCustomer(name: 'Dr Sudradjat', id: 'BGRSUDRA'),
  FinanceCustomer(name: 'Dr. Dwi Septiana', id: 'DWISEP'),
  FinanceCustomer(name: 'Dr. Egie', id: 'DREGIE'),
  FinanceCustomer(name: 'Dr. Herlambang', id: 'HERLAMBANG'),
  FinanceCustomer(name: 'Dr. Isa A.R', id: 'DRISA'),
  FinanceCustomer(name: 'Dr. Juliana', id: 'BTMJULIA'),
  FinanceCustomer(name: 'DWI RUSMANTO', id: 'DWI'),
  FinanceCustomer(name: 'EDI SUSILO', id: 'EDI SUSILO'),
  FinanceCustomer(name: 'Edy Prasetijo', id: 'BPEDYPRASE'),
  FinanceCustomer(name: 'Edy', id: 'BPEDY'),
  FinanceCustomer(name: 'EMYLVA RAMADHONA', id: 'ER'),
  FinanceCustomer(name: 'ENSEVAL PUTERA MEGATRADING TBK.', id: 'ENSEVAL'),
  FinanceCustomer(name: 'Erika Firdaus', id: 'IBUERIKA'),
  FinanceCustomer(name: 'ERIN WIDYAWATI', id: 'ERIN'),
  FinanceCustomer(name: 'FEBRY SETYAWAN', id: 'FEBRY'),
  FinanceCustomer(name: 'Felix', id: 'BPFELIX'),
  FinanceCustomer(name: 'Firdaus', id: 'BPFIRDAUS'),
  FinanceCustomer(name: 'FRANSISKA', id: 'FRANSISKA'),
  FinanceCustomer(name: 'Giza Nur Afinda', id: 'BPGIZA'),
  FinanceCustomer(name: 'Handoyo', id: 'BPHANDOYO'),
  FinanceCustomer(name: 'Hardi', id: 'BPHARDI'),
  FinanceCustomer(name: 'Harih', id: 'BPHARIH'),
  FinanceCustomer(name: 'Hasan Karna', id: 'BPHASAN'),
  FinanceCustomer(name: 'HEMMY PRASETYA SF.APT', id: 'HEMMY'),
  FinanceCustomer(name: 'HENDRA SALIM', id: 'HENDRA'),
  FinanceCustomer(name: 'HERI PRASETYO', id: 'BPHERI'),
  FinanceCustomer(name: 'HERMANTO WIDJAJA', id: 'HW'),
  FinanceCustomer(name: 'Hermanto', id: 'BPHERMANTO'),
  FinanceCustomer(name: 'HERU PRASONGKO', id: 'HERU'),
  FinanceCustomer(name: 'Hidayat Raharjo Utomo', id: 'BPJOJO'),
  FinanceCustomer(name: 'HLG (HARMONI LINTAS GAYA)', id: 'YBCR03'),
  FinanceCustomer(name: 'HR Medical', id: 'HRM'),
  FinanceCustomer(name: 'HUI HUANG ENTERPRISE', id: 'HHE'),
  FinanceCustomer(name: 'Ibu Ike', id: 'IKEHO'),
  FinanceCustomer(name: 'Ibu Lanany', id: 'LANANI'),
  FinanceCustomer(name: 'IBU MIRA', id: 'IBUMIRA'),
  FinanceCustomer(name: 'IDA SUHARDIAH', id: 'IDA S'),
  FinanceCustomer(name: 'Indra Susilowati', id: 'IBUINDRAS'),
  FinanceCustomer(name: 'Indra', id: 'IBUINDRA'),
  FinanceCustomer(name: 'INGGIA PUSPITA TAN', id: 'INGGIA'),
  FinanceCustomer(name: 'INGGIA PUSPITA', id: 'IBUINGGIA'),
  FinanceCustomer(name: 'IRA MURDIYANINGSIH', id: 'IRA M'),
  FinanceCustomer(name: 'ISKANDAR IDRIS', id: 'ISKANDAR'),
  FinanceCustomer(name: 'Jeane Rorimpandey', id: 'IBUJEANE'),
  FinanceCustomer(name: 'Jemi Mulyadi', id: 'BPJEMI'),
  FinanceCustomer(name: 'JUHARDI', id: 'JUHARDI'),
  FinanceCustomer(name: 'Karpe', id: 'BPKARPE'),
  FinanceCustomer(name: 'Ketut', id: 'BPKETUT'),
  FinanceCustomer(name: 'KHOE LIE PIENG', id: 'LIE PIENG'),
  FinanceCustomer(name: 'Klinik Gracia', id: 'KG'),
  FinanceCustomer(name: 'Kurniawan', id: 'BPKURNIAWA'),
  FinanceCustomer(name: 'LAIKA INTAN FATIYANI', id: 'LAIKA'),
  FinanceCustomer(name: 'LAVIE BABY HOUSE', id: 'YBCR04'),
  FinanceCustomer(name: 'LILIK TRIYANTO', id: 'LILIK'),
  FinanceCustomer(name: 'Lisa Nastasia', id: 'IBULISA'),
  FinanceCustomer(name: 'LISA RIZKI DWI PRATIWI', id: 'LISA'),
  FinanceCustomer(name: 'Lusa Mara', id: 'BPLUSA'),
  FinanceCustomer(name: 'LUTHFIA NURUL ANWAR', id: 'LUTHFIA'),
  FinanceCustomer(name: 'Marketing Ethical', id: 'MKT-ETH'),
  FinanceCustomer(name: 'MARSHALL SALI SOLIHIN', id: 'MARSHALL'),
  FinanceCustomer(name: 'Mentari', id: 'IBUMENTARI'),
  FinanceCustomer(name: 'Minyanto', id: 'BPMINYANTO'),
  FinanceCustomer(name: 'MUCHLIS MUHAMMAD', id: 'MUCHLIS'),
  FinanceCustomer(name: 'MUHAMMAD ALFIAN RAMADHAN', id: 'M.ALFIAN'),
  FinanceCustomer(name: 'Muhammad Rusdi', id: 'BPRUSDI'),
  FinanceCustomer(name: 'MUTIARA HASANAH', id: 'MUTIARA'),
  FinanceCustomer(name: 'Nanci', id: 'IBUNANCI'),
  FinanceCustomer(name: 'NUNUNG PAMUNGKAS', id: 'NUNUNG P'),
  FinanceCustomer(name: 'PAIDI', id: 'PAIDI'),
  FinanceCustomer(name: 'Pang Hok Kio', id: 'BPPANG'),
  FinanceCustomer(name: 'PEMBELIAN CASH', id: 'CASH'),
  FinanceCustomer(name: 'PINJAMAN', id: 'PINJAM'),
  FinanceCustomer(name: 'PRANITA DARA AYU', id: 'PDA'),
  FinanceCustomer(name: 'Prasetyo', id: 'BPPRASETYO'),
  FinanceCustomer(name: 'Prof Marcellus S.Sp.PD-KGEH', id: 'PROFMARCEL'),
  FinanceCustomer(name: 'Prof. Arif', id: 'PROFARIF'),
  FinanceCustomer(name: 'PROMOTION', id: 'PR'),
  FinanceCustomer(name: 'PT EDUKASI PUTRA MANDIRI', id: 'YBCR09'),
  FinanceCustomer(name: 'PT HARJA GUNATAMA LESTARI', id: 'YBCR10'),
  FinanceCustomer(name: 'PT MULTITREND INDO', id: 'YBCR02'),
  FinanceCustomer(name: 'PT,. BORNEO HARAPAN INSANI', id: 'BORNEO'),
  FinanceCustomer(name: 'PT. ADITYA FARMATAMA', id: 'ADF'),
  FinanceCustomer(name: 'PT. ALFA FARMATALIA', id: 'AF'),
  FinanceCustomer(name: 'PT. ANTARMITRA SEMBADA', id: 'AMS'),
  FinanceCustomer(name: 'PT. ARJUNA PRIMA PERKASA', id: 'APP'),
  FinanceCustomer(name: 'PT. BALI CAKRA KUSUMA', id: 'BCK'),
  FinanceCustomer(name: 'PT. BALI WAHYU ABADI', id: 'BWA'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BR'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRKDS'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRMGL'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRP'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRPW'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRSL'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRTG'),
  FinanceCustomer(name: 'PT. BATU RUSA', id: 'BRY'),
  FinanceCustomer(name: 'PT. BIO FARMA (PERSERO)', id: 'BF'),
  FinanceCustomer(name: 'PT. CAHYA WIRA BUANA', id: 'CWB'),
  FinanceCustomer(name: 'PT. CIF Transportasi Indonesia', id: 'CTI'),
  FinanceCustomer(name: 'PT. CITA SWARA SEJAHTERA', id: 'CSS'),
  FinanceCustomer(name: 'PT. CITRA NUSA INSAN CEMERLANG', id: 'CNI'),
  FinanceCustomer(name: 'PT. CITRA NUSA INSAN CEMERLANG', id: 'CNIB'),
  FinanceCustomer(name: 'PT. CITRA SEDAYUH', id: 'CS'),
  FinanceCustomer(name: 'PT. COMBI PUTRA MANDIRI', id: 'CP'),
  FinanceCustomer(name: 'PT. COMBI PUTRA', id: 'CPB'),
  FinanceCustomer(name: 'PT. CUBIX MULTI KREASI', id: 'PT.CMK'),
  FinanceCustomer(name: 'PT. DAYAANUGERAH DEWATASAKTI', id: 'DAD'),
  FinanceCustomer(name: 'PT. ENGGAL PERDANA', id: 'EP'),
  FinanceCustomer(
    name: 'PT. EQUALINDO MAKMUR ALAM SEJAHTERA',
    id: 'PT E M A S',
  ),
  FinanceCustomer(name: 'PT. FERTOMULIA PRATAMA', id: 'FP'),
  FinanceCustomer(name: 'PT. GATRA MORA', id: 'GM'),
  FinanceCustomer(name: 'PT. GLORIENTA PANCA HENNA', id: 'GPH'),
  FinanceCustomer(name: 'PT. INSULAR MULTI NATURAL', id: 'IMN'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPBDG'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPBJM'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPBKS'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPCRB'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPDPS'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPJ'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPJKS'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPJKT'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPKDR'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPMDN'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPMLG'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPPKB'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPPLB'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPSBY'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPSMD'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPSMG'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPTGR'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPUJP'),
  FinanceCustomer(name: 'PT. KALLISTA PRIMA', id: 'KPYYK'),
  FinanceCustomer(name: 'PT. KEDATON FARMA', id: 'KF'),
  FinanceCustomer(name: 'PT. KIMIA FARMA TRADING & DISTRIBUTION', id: 'KFA'),
  FinanceCustomer(name: 'PT. KIMIA FARMA TRADING & DISTRIBUTION', id: 'KFJ'),
  FinanceCustomer(name: 'PT. KIMIA FARMA TRADING & DISTRIBUTION', id: 'KFP'),
  FinanceCustomer(name: 'PT. KIMIA FARMA TRADING & DISTRIBUTION', id: 'KFPP'),
  FinanceCustomer(name: 'PT. KIMIA FARMA TRADING & DISTRIBUTION', id: 'KFTD'),
  FinanceCustomer(name: 'PT. LADANG MITABU', id: 'LM'),
  FinanceCustomer(name: 'PT. MENITI JALAN SURGA', id: 'MJS'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSB'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSBGR'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSBJR'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSBL'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSBTM'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSC'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSJ'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSJ2'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSJ3'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSJ4'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSJB'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSM'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSMDO'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSML'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSNAD'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSP'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSPB'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSPDG'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSPTK'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSSL'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSSM'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSSMD'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSSR'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSTK'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSUP'),
  FinanceCustomer(name: 'PT. MENSA BINASUKSES', id: 'MBSY'),
  FinanceCustomer(name: 'PT. METISKA FARMA ALKES', id: 'MALK'),
  FinanceCustomer(name: 'PT. METISKA FARMA', id: 'MF'),
  FinanceCustomer(name: 'PT. METISKA INTERNATIONAL TRADING', id: 'MIT'),
  FinanceCustomer(
    name: 'PT. MILLENNIUM PHARMACON INTERNATIONAL Tbk.',
    id: 'MPI',
  ),
  FinanceCustomer(
    name: 'PT. MILLENNIUM PHARMACON INTERNATIONAL Tbk.',
    id: 'MPIB',
  ),
  FinanceCustomer(name: 'PT. MODERN ABADI', id: 'MA'),
  FinanceCustomer(name: 'PT. MUGI WARAS MANDIRI', id: 'MWM'),
  FinanceCustomer(name: 'PT. MULTI HUSADA FARMA', id: 'MH'),
  FinanceCustomer(name: 'PT. MULTI HUSADA FARMA', id: 'MHB'),
  FinanceCustomer(name: 'PT. NAVITA INTI PRIMA', id: 'NIP'),
  FinanceCustomer(name: 'PT. NEW ASIAPHARM', id: 'NAP'),
  FinanceCustomer(name: 'PT. PALAPA KERAMIK GRANIT', id: 'PKG'),
  FinanceCustomer(name: 'PT. PENTA VALENT TBK', id: 'PVB'),
  FinanceCustomer(name: 'PT. PENTA VALENT TBK', id: 'PVBGR'),
  FinanceCustomer(name: 'PT. PENTA VALENT TBK', id: 'PVJ'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVBJR'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVBL'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVBTM'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVC'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVJ2'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVJ4'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVJB'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVJBR'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVKD'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVKDI'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVKPG'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVM'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVML'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVMND'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVMTR'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVMTRM'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVNAD'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVP'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVPB'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVPDG'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVPL'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVPTK'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVPW'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVSL'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVSM'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVSMD'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVSR'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVTG'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVTK'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVTSM'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVUP'),
  FinanceCustomer(name: 'PT. PENTA VALENT', id: 'PVY'),
  FinanceCustomer(name: 'PT. PRATAPA NIRMALA', id: 'PN'),
  FinanceCustomer(name: 'PT. PRESTASI INDOTAMA', id: 'PI'),
  FinanceCustomer(name: 'PT. PRIMA CHRISTOFARM', id: 'PC'),
  FinanceCustomer(name: 'PT. SAMMARIE TRAMEDIFA', id: 'STM'),
  FinanceCustomer(name: 'PT. SAPTA SARI TAMA', id: 'SST'),
  FinanceCustomer(name: 'PT. SIDHARTA HUSADA', id: 'SH'),
  FinanceCustomer(name: 'PT. SIGNA HUSADA', id: 'SHU'),
  FinanceCustomer(name: 'PT. SINGGASANA WITRA SURYAMAS', id: 'SWS'),
  FinanceCustomer(name: 'PT. TEGUHSINDO LESTARITAMA', id: 'TL'),
  FinanceCustomer(name: 'PT. TNT Skypak International Express', id: 'TSIE'),
  FinanceCustomer(name: 'PT. TRI SAPTA JAYA', id: 'TSJ'),
  FinanceCustomer(name: 'PT. TRI SAPTA JAYA', id: 'TSJB'),
  FinanceCustomer(name: 'PT. WAHANA SUMBER MEDIKA FARMA', id: 'WAHANA'),
  FinanceCustomer(name: 'PT. WAHYU CAHAYA BALI', id: 'WCB'),
  FinanceCustomer(name: 'PT. WAISAKA ANUGRAHPHARMA', id: 'WF'),
  FinanceCustomer(name: 'PT.ANTARMITRA SEMBADA', id: 'AMSB'),
  FinanceCustomer(name: 'PT.CORSA INDUSTRIES', id: 'CI'),
  FinanceCustomer(name: 'PT.EDNOVATE INDONESIA', id: 'PT.EDNO'),
  FinanceCustomer(name: 'PT.EDUKASI PUTRA MANDIRI', id: 'EPM'),
  FinanceCustomer(name: 'PT.ENSEVAL PUTERA MEGATRADING TBK', id: 'ENSEVAL 1'),
  FinanceCustomer(name: 'PT.ENSEVAL PUTERA MEGATRADING TBK', id: 'ENSEVAL 2'),
  FinanceCustomer(name: 'PT.ETERNEL INDONESIA', id: 'PT.E I'),
  FinanceCustomer(name: 'PT.GOGOBLI ASIA TEKNOLOGI', id: 'GGAT'),
  FinanceCustomer(name: 'PT.LOTTE SHOPPING AVENUE INDONESIA', id: 'LSAI'),
  FinanceCustomer(name: 'PT.MECOSIN INDONESIA', id: 'M I'),
  FinanceCustomer(name: 'PT.MEGASETIA AGUNG KIMIA', id: 'MAK'),
  FinanceCustomer(name: 'PT.MITRA BELANJA PERKASA', id: 'MBP'),
  FinanceCustomer(name: 'PT.MULTITREND INDO', id: 'MTI'),
  FinanceCustomer(name: 'PT.PASOKA SUMBER KARYA', id: 'PT.PSK'),
  FinanceCustomer(name: 'PT.PHYTO KEMO AGUNG FARMA', id: 'PKAF'),
  FinanceCustomer(name: 'PT.PRATAPA NIRMALA', id: 'PT.PN'),
  FinanceCustomer(name: 'PT.PRISMA PHARMA INTERNUSA', id: 'PT.P P I'),
  FinanceCustomer(name: 'PT.SOLUSI PRIMA VISITAMA', id: 'SOLUSI'),
  FinanceCustomer(name: 'PT.SUMBER ANEKA KARUNIA ABADI', id: 'SAKA'),
  FinanceCustomer(name: 'PT.SYDNA FARMA', id: 'SYF'),
  FinanceCustomer(name: 'PT.TITIAN ABADI LESTARI', id: 'PTTAL'),
  FinanceCustomer(name: 'Purwanti', id: 'IBUPURWAN'),
  FinanceCustomer(name: 'Puskesmas Pasirian', id: 'PASIRIAN'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. BANJARMASIN', id: 'RDIBJM'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. BANTEN', id: 'RDIBTN'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. JAMBI', id: 'RDIJMB'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. JAWA BARAT', id: 'RDIJBR'),
  FinanceCustomer(
    name: 'RDI INDONESIA CAB. KALIMANTAN TENGAH',
    id: 'RDIKALTENG',
  ),
  FinanceCustomer(name: 'RDI INDONESIA CAB. KALIMANTAN TIMUR', id: 'RDIKALTIM'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. MAKASAR', id: 'RDIMKS'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. MAROS', id: 'RDIMAROS'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. MEDAN', id: 'RDIMDN'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. PADANG', id: 'RDIPDG'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. PALEMBANG', id: 'RDIPLM'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. RIAU', id: 'RDIRIAU'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. SEMARANG', id: 'RDISMG'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. SOLO', id: 'RDISLO'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. SURABAYA', id: 'RDISBY'),
  FinanceCustomer(name: 'RDI INDONESIA CAB. YOGYAKARTA', id: 'RDIYOG'),
  FinanceCustomer(name: 'RDI INDONESIA', id: 'RDI'),
  FinanceCustomer(name: 'RIA OCTAVIANI SETIAWAN', id: 'RIA O S'),
  FinanceCustomer(name: 'RIA OCTAVIANI', id: 'YBCR01.'),
  FinanceCustomer(name: 'RIA OCTAVIANI', id: 'YBCR01'),
  FinanceCustomer(name: 'RIFKI SUKMA RAMDHANI', id: 'RIFKI'),
  FinanceCustomer(name: 'Ritwan Kurniawan', id: 'BPRITWAN'),
  FinanceCustomer(name: 'RIVANDA ADAM BRAMASTYA', id: 'RIVANDA'),
  FinanceCustomer(name: 'Robbie', id: 'BPROBBIE'),
  FinanceCustomer(name: 'ROBI YANTO', id: 'BPROBI'),
  FinanceCustomer(name: 'RONY YUNIANTO', id: 'RONY'),
  FinanceCustomer(name: 'RS Siaga Medika', id: 'JTGRSSIA'),
  FinanceCustomer(name: 'RS. YOS SUDARSO', id: 'RSYOS'),
  FinanceCustomer(name: 'RSUD MAGETAN', id: 'RSUDMGTN'),
  FinanceCustomer(name: 'Rumah Sakit Bersalin BUNDA', id: 'RBBUNDA'),
  FinanceCustomer(name: 'RUSDIANTO', id: 'RUSDI'),
  FinanceCustomer(name: 'RUSKI YANTO', id: 'RUSKI'),
  FinanceCustomer(name: 'RUTIN RUMAH SAKIT UMUM PANYABUNGAN', id: 'RRSUD'),
  FinanceCustomer(name: 'SAMPLE/DONASI', id: 'SAMPLE'),
  FinanceCustomer(name: 'Sendy', id: 'IBUSENDY'),
  FinanceCustomer(name: 'Sengnardi', id: 'BPSENGNAR'),
  FinanceCustomer(name: 'SENOR STO. NINO HOSPITAL', id: 'SSNH'),
  FinanceCustomer(name: 'Sephira Vitasari', id: 'IBUVITA'),
  FinanceCustomer(name: 'SETYO RINI BANGUN', id: 'SRB'),
  FinanceCustomer(name: 'Shelvy Angriawan', id: 'IBUSHELVY'),
  FinanceCustomer(name: 'SHELVY ANGRIAWAN', id: 'SHELVY'),
  FinanceCustomer(name: 'Sisca Utami', id: 'IBUSISCA'),
  FinanceCustomer(name: 'SITI HASSANAH ZAHRAH', id: 'IBUZAHRAH'),
  FinanceCustomer(name: 'SOFIA NOFRIDA.S.SI.APT', id: 'SOFIA'),
  FinanceCustomer(name: 'Sri Anjariah', id: 'IBUANJAR'),
  FinanceCustomer(name: 'SRI ANJARIYAH', id: 'SRI A'),
  FinanceCustomer(name: 'SRI PURWO NUGROHO', id: 'BPNUGROHO'),
  FinanceCustomer(name: 'Stefen', id: 'BPSTEFEN'),
  FinanceCustomer(name: 'Steve Yang', id: 'BPSTEVE'),
  FinanceCustomer(name: 'Sudianto', id: 'BPSUDI'),
  FinanceCustomer(name: 'SUKRON MAMUN', id: 'SUKRON'),
  FinanceCustomer(name: 'Sunaryadi Kurniawan', id: 'BPSUNAR'),
  FinanceCustomer(name: 'SUSANA PONDOK INDAH', id: 'YBCR001'),
  FinanceCustomer(name: 'Suzanna BSD', id: 'SBSSP'),
  FinanceCustomer(name: 'SUZANNA BSD', id: 'YBCR08'),
  FinanceCustomer(name: 'Suzanna Kelapa Gading', id: 'SBSKG'),
  FinanceCustomer(name: 'SUZANNA KELAPA GADING', id: 'YBCR07'),
  FinanceCustomer(name: 'Suzanna Pondok Indah', id: 'SBSPI'),
  FinanceCustomer(name: 'SUZANNA PONDOK INDAH', id: 'YBCR05'),
  FinanceCustomer(name: 'Suzanna Puri Indah', id: 'SBSPR'),
  FinanceCustomer(name: 'SUZANNA PURI INDAH', id: 'YBCR06'),
  FinanceCustomer(name: 'TAUFIK HARJITO', id: 'TAUFIK H'),
  FinanceCustomer(name: 'TEGUH SANTOSO', id: 'TEGUHS'),
  FinanceCustomer(name: 'THERESIA YULIANI', id: 'IBUESI'),
  FinanceCustomer(name: 'THERESIA YULIANI', id: 'TY'),
  FinanceCustomer(name: 'THY HOLDING GROUP CO.,LTD', id: 'THG'),
  FinanceCustomer(name: 'Tieke', id: 'IBUTIEKE'),
  FinanceCustomer(name: 'TIM PM', id: 'TIMPM'),
  FinanceCustomer(name: 'TO. RIZKI SEHAT', id: 'RIZ'),
  FinanceCustomer(name: 'TOMMY MARTIN', id: 'TOMMY'),
  FinanceCustomer(name: 'Tony Layardi', id: 'BPTONY'),
  FinanceCustomer(name: 'Trinayani', id: 'TRI'),
  FinanceCustomer(name: 'Trisnanto', id: 'BPTRISNANT'),
  FinanceCustomer(name: 'Turiman', id: 'BPTURIMAN'),
  FinanceCustomer(name: 'USHA NANDENI', id: 'USHA'),
  FinanceCustomer(name: 'UTAMI PRAVITASARI', id: 'UTAMI'),
  FinanceCustomer(name: 'VIPRIHATI JUNARIAH', id: 'IBUVIPRIHA'),
  FinanceCustomer(name: 'VIPRIHATI JUNARIAH', id: 'VIPRIHATI'),
  FinanceCustomer(name: 'Warjito', id: 'BPWARJITO'),
  FinanceCustomer(name: 'WIDIYATI', id: 'IBUWIDI'),
  FinanceCustomer(name: 'WILDAN ARISTYO', id: 'WILDAN'),
  FinanceCustomer(name: 'Willy', id: 'BPWILLY'),
  FinanceCustomer(name: 'Yanto', id: 'BPYANTO'),
  FinanceCustomer(name: 'Yohana', id: 'IBUYOHANA'),
];
