name: flexurio_erp_employee
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  dio: ^4.0.0
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  json_annotation: ^4.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  freezed: ^2.2.0
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  hive_generator: ^2.0.1
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: