part of 'menu.dart';

final menuPurchasing = Menu1(
  label: 'purchasing',
  menu: [
    flexurio_chiron_purchase_order.menu2Order,
    Menu2(
      label: 'Partners',
      icon: FontAwesomeIcons.handshake,
      menu: [
        Menu3(
          label: 'Fuel',
          home: const FuelPage(),
          permission: Permission.fuelViewMenu,
          permissions: [
            Permission.fuelViewMenu,
            Permission.fuelCreate,
            Permission.fuelDelete,
            Permission.fuelEdit,
          ],
        ),
        Menu3(
          label: 'Vehicle',
          home: const VehiclePage(),
          permission: Permission.vehicleViewMenu,
          permissions: [
            Permission.vehicleViewMenu,
            Permission.vehicleCreate,
            Permission.vehicleDelete,
            Permission.vehicleEdit,
            Permission.vehicleActive,
          ],
        ),
        Menu3(
          label: 'Vehicle Rent',
          home: const VehicleRentPage(),
          permission: Permission.vehicleRentViewMenu,
          permissions: [
            Permission.vehicleRentViewMenu,
            Permission.vehicleRentCreate,
            Permission.vehicleRentDelete,
            Permission.vehicleRentEdit,
            Permission.vehicleRentApproveCs,
            Permission.vehicleRentApproveManager,
            Permission.vehicleRentRejectCs,
            Permission.vehicleRentRejectManager,
            Permission.vehicleRentActualStartDate,
            Permission.vehicleRentActualEndDate,
            Permission.vehicleRentExportExcel,
          ],
        ),
        Menu3(
          label: 'purchase_request',
          home: PurchaseRequestPage.prepare(),
          permission: Permission.purchaseRequestViewMenu,
          permissions: [
            Permission.purchaseRequestViewMenu,
            Permission.purchaseRequestCreate,
            Permission.purchaseRequestDelete,
            Permission.purchaseRequestEdit,
            Permission.purchaseRequestExportPdf,
            Permission.purchaseRequestExportExcel,
            Permission.purchaseRequestDetailConfirm,
            Permission.purchaseRequestDetailReject,
            Permission.purchaseRequestDetailUndoConfirm,
            Permission.purchaseRequestDetailRejectForManager,
          ],
        ),
        Menu3(
          label: 'Request Form',
          home: RequestFormPage.prepare(),
          permission: Permission.requestFormViewMenu,
          permissions: [
            Permission.requestFormViewMenu,
            Permission.requestFormCreate,
            Permission.requestFormCreateMR,
            Permission.requestFormEdit,
            Permission.requestFormDetailConfirm,
            Permission.requestFormDetailDelete,
            Permission.requestFormClose,
            Permission.requestFormReject,
          ],
        ),
        Menu3(
          label: 'Manufacturer',
          home: const VendorPage(),
          permission: PermissionVendor.vendorViewMenu,
          permissions: [
            PermissionVendor.vendorViewMenu,
            PermissionVendor.vendorCreate,
            PermissionVendor.vendorDelete,
            PermissionVendor.vendorEdit,
          ],
        ),
        Menu3(
          label: 'Supplier',
          home: const SupplierPage(),
          permission: Permission.supplierViewMenu,
          permissions: [
            Permission.supplierViewMenu,
            Permission.supplierCreate,
            Permission.supplierDelete,
            Permission.supplierEdit,
            Permission.supplierExportExcel,
          ],
        ),
      ],
    ),
  ],
);
