# include: package:very_good_analysis/analysis_options.yaml
# linter:
#   rules:
#     public_member_api_docs: false
#     avoid_positional_boolean_parameters: false
#     prefer_constructors_over_static_methods: false
#     implementation_imports: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore