name: flexurio_no_code
description: A new Flutter project.

publish_to: "none"

version: 0.15.14-release-2024.06.27.05.01-GMT7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^4.0.0
  easy_localization: ^3.0.7
  flexurio_erp_core:
    path: packages/flexurio_erp_core/
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.1.10
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  intl: ^0.19.0
  json_annotation: ^4.7.0
  page_transition: ^2.0.9
  path_provider: ^2.0.9
  pattern_formatter:
    git:
      url: https://github.com/augustineonu/flutter_pattern_formatter.git
      ref: e310fc81043468b9b2b063bac6122f7dde51b03f
  screen_identifier: ^0.0.2
  go_router: ^14.3.0

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  icons_launcher: ^2.0.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/configuration/entity/
    - asset/configuration/
    - asset/html/
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "asset/image/logo.png"
  web:
    generate: true
    image_path: "asset/image/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/image/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "asset/image/logo.png"
