name: appointment
description: A new Flutter project.

publish_to: "none"

version: 0.15.14-release-2024.06.27.05.01-GMT7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter_offline: ^4.0.0
  animated_check: ^1.0.2
  animated_cross: ^1.0.0
  bloc_concurrency: ^0.2.1
  clipboard: ^0.1.3
  currency_text_input_formatter: ^2.1.10
  custom_sliding_segmented_control: ^1.8.0
  dio: ^4.0.0
  dropdown_search: ^5.0.5
  easy_image_viewer: ^1.2.1
  easy_localization: ^3.0.7
  equatable: ^2.0.3
  expandable: ^5.0.1
  file_picker: ^5.2.5
  flexurio_chiron_marketing:
    path: packages/flexurio_chiron_marketing/
  flexurio_chiron_vendor:
    path: packages/flexurio_chiron_vendor/
  flexurio_chiron_purchase_request:
    path: packages/flexurio_chiron_purchase_request/
  flexurio_chiron_accounting:
    path: packages/flexurio_chiron_accounting/
  flexurio_chiron_material:
    path: packages/flexurio_chiron_material/
  flexurio_chiron_material_stock:
    path: packages/flexurio_chiron_material_stock/
  flexurio_chiron_product:
    path: packages/flexurio_chiron_product/
  flexurio_chiron_product_stock:
    path: packages/flexurio_chiron_product_stock/
  flexurio_chiron_purchase_order:
    path: packages/flexurio_chiron_purchase_order/
  flexurio_chiron_production:
    path: packages/flexurio_chiron_production/
  flexurio_erp_authentication:
    path: packages/flexurio_erp_authentication/
  flexurio_erp_core:
    path: packages/flexurio_erp_core/
  flexurio_erp_employee:
    path: packages/flexurio_erp_employee/
  flexurio_chiron_finance:
    path: packages/flexurio_chiron_finance/
  flexurio_chiron_tax:
    path: packages/flexurio_chiron_tax/
  flexurio_chiron_sales_order:
    path: packages/flexurio_chiron_sales_order/
  flexurio_chiron_company:
    path: packages/flexurio_chiron_company/
  flexurio_chiron_presence:
    path: packages/flexurio_chiron_presence/
  flexurio_chiron_customer:
    path: packages/flexurio_chiron_customer/
  flexurio_chiron_ticket:
    path: packages/flexurio_chiron_ticket/
  flexurio_chiron_business_trip:
    path: packages/flexurio_chiron_business_trip/
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.1.10
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.0.5
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  horizontal_data_table: ^4.1.5
  hydrated_bloc: ^8.1.0
  image_network: ^2.5.4+1
  intl: ^0.19.0
  json_annotation: ^4.7.0
  just_audio: ^0.9.37
  just_audio_windows: ^0.2.1
  just_the_tooltip: ^0.0.12
  linked_scroll_controller: ^0.2.0
  mask_text_input_formatter: ^2.4.0
  package_info_plus: ^8.0.0
  page_transition: ^2.0.9
  path_provider: ^2.0.9
  pattern_formatter:
    git:
      url: https://github.com/augustineonu/flutter_pattern_formatter.git
      ref: e310fc81043468b9b2b063bac6122f7dde51b03f
  pdf: ^3.8.4
  pinput: ^2.2.31
  printing: ^5.10.4
  screen_identifier: ^0.0.2
  scroll_to_id: ^1.5.1
  syncfusion_flutter_calendar: ^28.1.33
  syncfusion_flutter_charts: ^28.1.33
  syncfusion_flutter_datepicker: ^28.1.33
  syncfusion_flutter_xlsio: ^28.1.33
  terbilang_id: ^0.1.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.8
  go_router: ^14.3.0

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  hive_generator: ^2.0.1
  icons_launcher: ^2.0.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "asset/image/logo.png"
  web:
    generate: true
    image_path: "asset/image/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "asset/image/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "asset/image/logo.png"
