name: flexurio_chiron_accounting
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  gap: ^3.0.1
  printing: ^5.10.4
  easy_localization: ^3.0.7
  pdf: ^3.8.4
  flutter_bloc: ^8.1.6
  appointment:
    path: ../../
  dio: ^4.0.0
  freezed_annotation: ^2.2.0
  syncfusion_flutter_datepicker: ^28.1.33
  flexurio_chiron_company:
    path: ../flexurio_chiron_company/
  flexurio_chiron_finance:
    path: ../flexurio_chiron_finance/
  flexurio_chiron_purchase_order:
    path: ../flexurio_chiron_purchase_order/
  flexurio_chiron_material:
    path: ../flexurio_chiron_material/
  flexurio_erp_authentication:
    path: ../flexurio_erp_authentication/
  flexurio_chiron_customer:
    path: ../flexurio_chiron_customer/
  flutter:
    sdk: flutter
  flexurio_erp_core:
    path: ../flexurio_erp_core/

dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/