import 'package:flx_nocode_flutter/src/app/bloc/entity/entity_bloc.dart';
import 'package:flx_nocode_flutter/src/app/model/entity.dart' as configuration;
import 'package:flx_nocode_flutter/src/app/model/layout.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flx_core_flutter/flx_core_flutter.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flx_nocode_flutter/src/app/view/page/entity_create/widget/form.dart';
import 'package:gap/gap.dart';
import 'package:page_transition/page_transition.dart';

class EntityCreatePage extends StatefulWidget {
  const EntityCreatePage._(
    this.data,
    this.entity,
    this.onSuccess,
    this.embedded,
  );

  final Map<String, dynamic>? data;
  final configuration.EntityCustom entity;
  final VoidCallback onSuccess;
  final bool embedded;

  static Route<bool?> route({
    required configuration.EntityCustom entity,
    Map<String, dynamic>? data,
    required VoidCallback onSuccess,
    required bool embedded,
  }) {
    return PageTransition(
      opaque: true,
      type: PageTransitionType.rightToLeft,
      child: MultiBlocProvider(
        providers: [BlocProvider(create: (_) => EntityBloc(entity))],
        child: EntityCreatePage._(data, entity, onSuccess, embedded),
      ),
    );
  }

  @override
  State<EntityCreatePage> createState() => _EntityCreatePageState();
}

class _EntityCreatePageState extends State<EntityCreatePage> {
  final _formKey = GlobalKey<FormState>();
  final _controllers = <String, TextEditingController>{};
  late DataAction _action;

  @override
  void initState() {
    super.initState();

    for (final field in widget.entity.fields) {
      _controllers[field.reference] = TextEditingController();
    }

    _action = createOrEdit(widget.data);
    if (_action.isEdit) {
      for (final field in widget.entity.fields) {
        _controllers[field.reference]!.text =
            widget.data![field.reference].toString();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final coreEntity = widget.entity.coreEntity;
    return BlocListener<EntityBloc, EntityState>(
      listener: (context, state) {
        state.maybeWhen(
          success: (_) {
            widget.onSuccess();
            Toast(context).dataChanged(_action, coreEntity);
            Navigator.pop(context, true);
          },
          error: (error) => Toast(context).fail(error),
          orElse: () {},
        );
      },
      child: Scaffold(
        appBar: widget.embedded ? _buildAppBar(context) : null,
        backgroundColor: widget.embedded ? theme.cardColor : Colors.transparent,
        body: SingleFormPanel(
          hideHeader: widget.embedded ? true : false,
          formKey: _formKey,
          action: _action,
          entity: coreEntity,
          actions: [_buildButtonSubmit()],
          children: [
            EntityCreateForm(
              entity: widget.entity,
              dataAction: _action,
              controllers: _controllers,
            )
          ],
        ),
      ),
    );
  }

  AppBar _buildAppBar(BuildContext context) {
    final theme = Theme.of(context);
    return AppBar(
      title: Text('${_action.title} ${widget.entity.coreEntity.title}'),
      backgroundColor: theme.scaffoldBackgroundColor,
    );
  }

  Map<String, dynamic> get _data {
    final data = <String, dynamic>{};
    for (final field in widget.entity.fields) {
      if (field.autoGenerated ?? false) {
        continue;
      }

      var value = _controllers[field.reference]!.text;
      if (field.isDateTime) {
        print(
          '[EntityCreatePage] reference: ${field.reference}, value: $value',
        );
        value = DateFormat('yMMMMd').parse(value).toUtcIso();
      }
      data[field.reference] = value;
    }
    return data;
  }

  void _submit() {
    if (_formKey.currentState!.validate()) {
      late EntityEvent event;
      if (_action.isEdit) {
        event = EntityEvent.edit(data: _data);
      } else {
        event = EntityEvent.create(data: _data);
      }

      context.read<EntityBloc>().add(event);
    }
  }

  Widget _buildButtonSubmit() {
    return BlocBuilder<EntityBloc, EntityState>(
      builder: (context, state) {
        return Button.action(
          permission: null,
          isInProgress: state.maybeWhen(
            loading: () => true,
            orElse: () => false,
          ),
          onPressed: _submit,
          action: _action,
        );
      },
    );
  }
}
