name: flexurio_erp_authentication
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.2.0
  hydrated_bloc: ^8.1.0
  pattern_formatter:
    git:
      url: https://github.com/augustineonu/flutter_pattern_formatter.git
      ref: e310fc81043468b9b2b063bac6122f7dde51b03f
  dio: ^4.0.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  go_router: ^14.3.0
 
dev_dependencies:
  build_runner_core: ^7.2.9
  build_runner: ^2.4.6
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
