import 'package:flutter_test/flutter_test.dart';

void main() {
  test('COGS Group', () {
    final data = {
      'success': true,
      'message': 'Record found',
      'data': [
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Beginning Balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 3148768300,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Purchase Baku',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 410544540,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Retur pembelian',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Raw Material Released dari PO sblmnya',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 367125340,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Raw Material Karantina',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -369562000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Others Raw Material Used',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -51831428,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Ending balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -4585088000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Pengembalian Baku Produk TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Adjustment Stok Tambah Baku',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 993771.9,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Adjustment Stok Minus Baku',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -222960.62,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'RAW MATERIAL (used)',
          'grade_4': 'Pemakaian Material Baku MF Oleh TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -6896834.5,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Beginning balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Purchase Bantu',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Retur pembelian',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Auxiliary Raw Material Released dari PO sblmnya',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Auxiliary Raw Material Karantina',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Others Auxiliary Raw Material Used',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Ending balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Pengembalian Bantu Produk TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Adjustment Stok Tambah Bantu',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Adjustment Stok Minus Bantu',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'AUXILIARY RAW MATERIAL (used)',
          'grade_4': 'Pemakaian Material Bantu MF Oleh TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Beginning balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Purchase Kemasan',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Retur pembelian',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Packaging Released dari PO sblmnya',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Packaging Karantina',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Others Packaging Used',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Ending balance',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Pengembalian Kemasan Produk TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Adjustment Stok Tambah Kemasan',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Adjustment Stok Minus Kemasan',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'PACKAGING (used)',
          'grade_4': 'Pemakaian Material Kemasan MF Oleh TL',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6010201',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 78024710,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6010301',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 90000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6010401',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 326590800,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6010501',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 2135865,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6010801',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 4095000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6012001',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6011501',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6012101',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 5800000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6012301',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 1100000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6041101',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 4100000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'DIRECT LABOR',
          'grade_4': '6012201',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 21925300,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6030302',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 28797048,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6030402',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 37806400,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6030502',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 4165100,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6030702',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 84469970,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6040102',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6040202',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 6918200,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6040502',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6010202',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 462672000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6010302',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 3792456,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6010402',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 117539050,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6010502',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 1922913,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6010802',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 23310000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6021802',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 41525856,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6012002',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6021702',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 35750000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6011502',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 11250000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6041002',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 106140000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6012202',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 28792650,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6012102',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 25100000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'TOTAL PRODUCTION COST',
          'grade_3': 'FACTORY OVERHEAD',
          'grade_4': '6012302',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 8400000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Beginning balance, WIP',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Other`s WIP Out',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -12017778,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Jasa maklon produk Ethical TL di MF',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Ending balance, WIP',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Balance Jasa maklon produk Ethical TL di MF',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Balance Other`s WIP Out',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 12017778,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Pengembalian material produk release ',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Penambahan Material Produk Sudah Rilis',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS MANUFACTURING (COGM)',
          'grade_2': 'Biaya Parsial Bulan Sebelumnya',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Beginning balance, FG',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 4901081600,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Purhase Ethical from TL',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 914823000,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Purhase Purastat',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Purchase BloodSTOP',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 80080900,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Retur penjualan',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Others FG Out',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -124209050,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Ending balance, FG',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': -5552220700,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Pembelian Toll Out',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 630032260,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'Jurnal Selisih',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'FG Parsial Bulan Sebelumnya',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        },
        {
          'grade_1': 'COST OF GOODS SOLD (COGS)',
          'grade_2': 'FG Parsial Bulan Setelahnya',
          'grade_3': '',
          'grade_4': '',
          'year': 2022,
          'division': '01',
          'jan': 0,
          'feb': 0,
          'mar': 0,
          'apr': 0,
          'may': 0,
          'jun': 0,
          'jul': 0,
          'aug': 0,
          'sep': 0,
          'oct': 0,
          'nov': 0,
          'des': 0,
        }
      ],
    };

    // final cogsData = <CogsRaw>[];
    // for (final data in data['data']! as List) {
    //   cogsData.add(CogsRaw.fromJson(data as Map<String, dynamic>));
    // }

    // final cogsResult = cogsGroup(cogsData);

    // print(cogsResult);
  });
}
