import 'package:flexurio_chiron_finance/src/app/model/cash_flow_code.dart';
import 'package:flexurio_chiron_finance/src/app/view/page/cash_flow/util/generate_code_and_sub_code.dart';
import 'package:flutter_test/flutter_test.dart';

DateTime dt = DateTime.parse('0001-01-01T00:00:00Z');
final List<CashFlowCode> data = [
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'Cash/Tunai ',
    amount: 0,
    code: '1',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'PT. Dayaanugerah Dewata Sakti',
    amount: 0,
    code: '1',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'PT. Mensa Binasukses',
    amount: 0,
    code: '1',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'PT. MPI',
    amount: 0,
    code: '1',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'LBB',
    amount: 0,
    code: '2',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'Pengembalian Biaya Promosi',
    amount: 0,
    code: '2',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'Pengembalian BS MD',
    amount: 0,
    code: '2',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'Finish Good',
    amount: 0,
    code: '3',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
  CashFlowCode(
    date: '0001-01-01T00:00:00Z',
    noTransaction: '',
    invoice: '',
    recForm: '',
    description: 'lain-lain',
    amount: 0,
    code: '3',
    subCode: '',
    mutationDate: DateTime(2023, 8, 4),
    transferFee: 0,
    totalTransfer: 0,
    bank: '',
    status: '',
  ),
];

void main() {
  test(
    'generated code and sub code',
    () => {generateCodeAndSubCode(data)},
  );
}
