name: flexurio_chiron_production
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^2.2.0
  appointment:
    path: ../../
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner_core: ^7.2.9
  build_runner: ^2.4.6
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
