name: flexurio_chiron_customer
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  freezed_annotation: ^2.2.0
  flexurio_chiron_product:
    path: ../flexurio_chiron_product/
  flexurio_chiron_material:
    path: ../flexurio_chiron_material/
  flexurio_chiron_purchase_order:
    path: ../flexurio_chiron_purchase_order/
  appointment:
    path: ../../
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  flutter:
    sdk: flutter
  gap: ^3.0.1
  easy_localization: ^3.0.7
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  form_field_validator: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  page_transition: ^2.1.0
  syncfusion_flutter_xlsio: ^28.1.33
  hydrated_bloc: ^8.1.0

dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/