import 'package:hive_ce/hive.dart';

/// Represents a single field definition in a dynamic entity configuration.
///
/// This model describes how a field should be rendered, validated, and
/// whether it can be created/updated/copied inside UI or forms.
class EntityField extends HiveObject {
  /// Human-readable label to display in UI.
  final String label;

  /// Unique reference/key for the field.
  final String reference;

  /// Field type (e.g. "text", "number", "date", "select", etc).
  final String type;

  /// Optional width of the column when rendered in tables/grids.
  final double? columnWidth;

  /// Whether the field value is automatically generated.
  final bool? autoGenerated;

  /// Whether the field value is required.
  final bool required;

  /// Regex pattern for validating the field.
  final String? pattern;

  /// Error message shown if [pattern] does not match.
  final String? patternError;

  /// Source identifier for option-based fields.
  final String? optionsSource;

  /// Minimum text length for this field.
  final int? minLength;

  /// Maximum text length for this field.
  final int? maxLength;

  /// Whether this field is allowed to be set on create.
  final bool? allowCreate;

  /// Whether this field can be updated after creation.
  final bool? allowUpdate;

  /// Whether the field value can be copied from UI.
  final bool? isCopyable;

  /// Additional options for dropdown/lookup type fields.
  final FieldOptions? options;

  /// Creates a new [EntityField] configuration.
  EntityField({
    required this.label,
    required this.reference,
    required this.type,
    this.columnWidth,
    this.autoGenerated,
    this.required = false,
    this.pattern,
    this.patternError,
    this.optionsSource,
    this.minLength,
    this.maxLength,
    this.allowCreate,
    this.allowUpdate,
    this.isCopyable,
    this.options,
  });

  /// Creates an [EntityField] instance from JSON.
  ///
  /// Expected JSON structure:
  /// ```json
  /// {
  ///   "label": "Name",
  ///   "reference": "name",
  ///   "type": "text",
  ///   "column_width": 150,
  ///   "auto_generated": false,
  ///   "required": true,
  ///   "is_copyable": true
  /// }
  /// ```
  factory EntityField.fromJson(Map<String, dynamic> json) {
    return EntityField(
      optionsSource: json['options_source'] as String?,
      columnWidth: (json['column_width'] as num?)?.toDouble(),
      label: json['label'] as String? ?? '',
      reference: json['reference'] as String? ?? '',
      type: json['type'] as String? ?? '',
      autoGenerated: json['auto_generated'] as bool?,
      required: json['required'] as bool? ?? false,
      pattern: json['pattern'] as String?,
      patternError: json['pattern_error'] as String?,
      minLength: json['min_length'] as int?,
      maxLength: json['max_length'] as int?,
      allowCreate: json['allow_create'] as bool?,
      allowUpdate: json['allow_update'] as bool?,
      isCopyable: json['is_copyable'] as bool?,
    );
  }

  /// Creates an empty/default field.
  factory EntityField.empty() => EntityField(
        label: '',
        reference: '',
        type: '',
      );

  /// Returns a copy of this field with overridden values.
  EntityField copyWith({
    String? label,
    String? reference,
    String? type,
    double? columnWidth,
    bool? autoGenerated,
    bool? required,
    String? pattern,
    String? patternError,
    String? optionsSource,
    int? minLength,
    int? maxLength,
    bool? allowCreate,
    bool? allowUpdate,
    bool? isCopyable,
    FieldOptions? options,
  }) {
    return EntityField(
      label: label ?? this.label,
      reference: reference ?? this.reference,
      type: type ?? this.type,
      columnWidth: columnWidth ?? this.columnWidth,
      autoGenerated: autoGenerated ?? this.autoGenerated,
      required: required ?? this.required,
      pattern: pattern ?? this.pattern,
      patternError: patternError ?? this.patternError,
      optionsSource: optionsSource ?? this.optionsSource,
      minLength: minLength ?? this.minLength,
      maxLength: maxLength ?? this.maxLength,
      allowCreate: allowCreate ?? this.allowCreate,
      allowUpdate: allowUpdate ?? this.allowUpdate,
      isCopyable: isCopyable ?? this.isCopyable,
      options: options ?? this.options,
    );
  }

  /// Converts this field definition into JSON map.
  Map<String, dynamic> toJson() {
    return {
      'options_source': optionsSource,
      'column_width': columnWidth,
      'label': label,
      'reference': reference,
      'type': type,
      'auto_generated': autoGenerated,
      'required': required,
      'pattern': pattern,
      'pattern_error': patternError,
      'min_length': minLength,
      'max_length': maxLength,
      'allow_create': allowCreate,
      'allow_update': allowUpdate,
      'is_copyable': isCopyable,
    };
  }
}

/// Options configuration for dropdown/lookup fields.
class FieldOptions extends HiveObject {
  /// Source of data (API endpoint, Hive box, etc).
  final String source;

  /// Field to show as label when rendering options.
  final String labelField;

  /// Field used as value in selection.
  final String valueField;

  FieldOptions({
    required this.source,
    required this.labelField,
    required this.valueField,
  });

  /// Creates a [FieldOptions] instance from JSON.
  factory FieldOptions.fromJson(Map<String, dynamic> json) {
    return FieldOptions(
      source: json['source'] as String? ?? '',
      labelField: json['label_field'] as String? ?? '',
      valueField: json['value_field'] as String? ?? '',
    );
  }

  /// Converts this options configuration into JSON map.
  Map<String, dynamic> toJson() {
    return {
      'source': source,
      'label_field': labelField,
      'value_field': valueField,
    };
  }
}
