import 'package:hive_ce/hive.dart';

class EntityField extends HiveObject {
  final String label;
  final String reference;
  final String type;
  final double? columnWidth;
  final bool? autoGenerated;
  final bool required;
  final String? pattern;
  final String? patternError;
  final String? optionsSource;
  final int? minLength;
  final int? maxLength;
  final bool? allowCreate;
  final bool? allowUpdate;
  final FieldOptions? options;

  EntityField({
    required this.label,
    required this.reference,
    required this.type,
    this.required = false,
    this.columnWidth,
    this.autoGenerated,
    this.pattern,
    this.patternError,
    this.optionsSource,
    this.minLength,
    this.maxLength,
    this.allowCreate,
    this.allowUpdate,
    this.options,
  });

  factory EntityField.fromJson(Map<String, dynamic> json) {
    return EntityField(
      optionsSource: json['options_source'] as String?,
      columnWidth: (json['column_width'] as num?)?.toDouble(),
      label: json['label'] as String? ?? '',
      reference: json['reference'] as String? ?? '',
      type: json['type'] as String? ?? '',
      autoGenerated: json['auto_generated'] as bool?,
      required: json['required'] as bool? ?? false,
      pattern: json['pattern'] as String?,
      patternError: json['pattern_error'] as String?,
      minLength: json['min_length'] as int?,
      maxLength: json['max_length'] as int?,
      allowCreate: json['allow_create'] as bool?,
      allowUpdate: json['allow_update'] as bool?,
    );
  }

  factory EntityField.empty() => EntityField(
        label: '',
        reference: '',
        type: '',
      );

  EntityField copyWith({
    String? label,
    String? reference,
    String? type,
    double? columnWidth,
    bool? autoGenerated,
    bool? required,
    String? pattern,
    String? patternError,
    String? optionsSource,
    int? minLength,
    int? maxLength,
    bool? allowCreate,
    bool? allowUpdate,
    FieldOptions? options,
  }) {
    return EntityField(
      label: label ?? this.label,
      reference: reference ?? this.reference,
      type: type ?? this.type,
      columnWidth: columnWidth ?? this.columnWidth,
      autoGenerated: autoGenerated ?? this.autoGenerated,
      required: required ?? this.required,
      pattern: pattern ?? this.pattern,
      patternError: patternError ?? this.patternError,
      optionsSource: optionsSource ?? this.optionsSource,
      minLength: minLength ?? this.minLength,
      maxLength: maxLength ?? this.maxLength,
      allowCreate: allowCreate ?? this.allowCreate,
      allowUpdate: allowUpdate ?? this.allowUpdate,
      options: options ?? this.options,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'options_source': optionsSource,
      'column_width': columnWidth,
      'label': label,
      'reference': reference,
      'type': type,
      'auto_generated': autoGenerated,
      'required': required,
      'pattern': pattern,
      'pattern_error': patternError,
      'min_length': minLength,
      'max_length': maxLength,
      'allow_create': allowCreate,
      'allow_update': allowUpdate,
    };
  }
}

class FieldOptions extends HiveObject {
  final String source;
  final String labelField;
  final String valueField;

  FieldOptions({
    required this.source,
    required this.labelField,
    required this.valueField,
  });

  factory FieldOptions.fromJson(Map<String, dynamic> json) {
    return FieldOptions(
      source: json['source'] as String? ?? '',
      labelField: json['label_field'] as String? ?? '',
      valueField: json['value_field'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'source': source,
      'label_field': labelField,
      'value_field': valueField,
    };
  }
}
