name: flexurio_erp_core
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  hydrated_bloc: ^8.1.0
  pattern_formatter:
    git:
      url: https://github.com/augustineonu/flutter_pattern_formatter.git
      ref: e310fc81043468b9b2b063bac6122f7dde51b03f
  pinput: ^2.2.31
  flutter_bloc: ^8.1.6
  glass: ^1.0.2+1
  pdf: ^3.8.4
  package_info_plus: ^8.0.0
  currency_text_input_formatter: ^2.1.10
  syncfusion_flutter_datepicker: ^28.1.33
  timeline_tile: ^2.0.0
  animated_check: ^1.0.2
  flutter_svg: ^2.0.5
  page_transition: ^2.0.9
  animated_cross: ^1.0.0
  just_audio: ^0.9.37
  just_audio_windows: ^0.2.1
  month_picker_dialog: ^4.0.1
  file_picker: ^5.2.5
  dotted_border: ^2.1.0
  syncfusion_flutter_charts: ^28.1.33
  fluttertoast: ^8.0.8
  clipboard: ^0.1.3
  dropdown_search: ^5.0.5
  dio: ^4.0.0
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  google_fonts: ^4.0.4
  hive: ^2.2.3
  screen_identifier: ^0.0.2
  side_panel: ^0.0.1
  form_field_validator: ^1.1.0
  syncfusion_flutter_xlsio: ^28.1.33
  printing: ^5.10.4
  go_router: ^14.3.0
 
dev_dependencies:
  build_runner_core: ^7.2.9
  build_runner: ^2.4.6
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/