import 'dart:typed_data';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/pdf_image_service.dart';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/strategies/canvas_layout_strategy.dart';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/strategies/document_layout_strategy.dart';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/strategies/pdf_layout_strategy.dart'
    show PdfLayoutStrategy;
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/utils/pdf_data_utils.dart';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/utils/pdf_interpolation_utils.dart';
import 'package:flx_nocode_flutter/features/print/domain/pdf_generator/utils/pdf_unit_utils.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'package:flx_nocode_flutter/shared/services/http_request_executor.dart';

class JsonPdfGenerator {
  /// Generates a PDF document from the provided LayoutPrint JSON specification.
  static Future<Uint8List> generate(
    Map<String, dynamic> json, {
    Map<String, dynamic>? data,
    HttpRequestExecutor? executor,
  }) async {
    try {
      // 1. Initialize data context
      final Map<String, dynamic> contextData =
          data != null ? Map<String, dynamic>.from(data) : {};

      // 2. Fetch all http_data recursively
      await PdfDataUtils.fetchAllHttpData(json, contextData,
          executor: executor);

      // 3. Interpolate the JSON with the final data context
      final processed =
          PdfInterpolationUtils.interpolateJson(json, contextData);
      final Map<String, dynamic> processedJson = processed is Map
          ? Map<String, dynamic>.from(processed)
          : Map<String, dynamic>.from(json);

      // 4. Initialize PDF Document
      final pdf = pw.Document();
      final layoutType = processedJson['layout_type']?.toString() ?? 'canvas';
      final unit = processedJson['unit']?.toString() ?? 'pt';

      // 5. Parse Page Format
      PdfPageFormat format =
          PdfUnitUtils.parsePageSize(processedJson['page_size'], unit);
      if (processedJson['orientation'] == 'landscape') {
        format = format.landscape;
      }

      // 6. Pre-load Images
      final imageService = PdfImageService();
      final imageCache = await imageService.loadImages(processedJson);

      // 7. Extract Global Header/Footer
      final dynamic rawHeader = processedJson['header'];
      final List<dynamic> globalHeader = rawHeader is List ? rawHeader : [];
      final dynamic rawFooter = processedJson['footer'];
      final List<dynamic> globalFooter = rawFooter is List ? rawFooter : [];

      // 8. Select and Execute Strategy
      final PdfLayoutStrategy strategy = layoutType == 'document'
          ? DocumentLayoutStrategy()
          : CanvasLayoutStrategy();

      await strategy.build(
        pdf: pdf,
        processedJson: processedJson,
        format: format,
        unit: unit,
        imageCache: imageCache,
        globalHeader: globalHeader,
        globalFooter: globalFooter,
      );

      // 9. Return Generated Bytes
      return await pdf.save();
    } catch (e, stack) {
      print('PDF Generation Error: $e');
      print(stack);
      rethrow;
    }
  }
}
