name: flexurio_chiron_marketing
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  appointment:
    path: ../../
  dio: ^4.0.0
  easy_localization: ^3.0.7
  flexurio_erp_authentication:
    path: ../flexurio_erp_authentication/
  flexurio_erp_core:
    path: ../flexurio_erp_core/
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  hydrated_bloc: ^8.1.0
  intl: ^0.19.0
  json_annotation: ^4.7.0
  screen_identifier: ^0.0.2
  syncfusion_flutter_charts: ^28.1.33

dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/
